# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4c2632f5c2bc6685d3b1568290f8886c3209e0ae5fcd22537e9c97b0888c5b5359a9236e79a8bc8241eef895598a771e1eb9decfe24c92404ad3cb2f2115d8

test:
  secret_key_base: 90389d29aaeee4d4c4dc452a27c1a96bdb29a03b35f5057858db82bdb12c7ca0d4e5850abca304cad86ab3b12dd39283a48bc925a577eb195e14dc53f3c8e97d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
